//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayOfficev2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEspacio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEspacio()
        {
            this.tblAmenidadEspacio = new HashSet<tblAmenidadEspacio>();
            this.tblReservas = new HashSet<tblReservas>();
        }
    
        public int IdEspacio { get; set; }
        public int IdUsuario { get; set; }
        public string NombreEspacio { get; set; }
        public double LatitudEspacio { get; set; }
        public double LongitudEspacio { get; set; }
        public double Costo { get; set; }
        public Nullable<double> Puntaje { get; set; }
        public Nullable<double> VelocidadInternet { get; set; }
        public Nullable<int> Selected { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAmenidadEspacio> tblAmenidadEspacio { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReservas> tblReservas { get; set; }
    }
}
